import os
import json
import shutil
import subprocess
import logging

logger = logging.getLogger(__name__)

# The node script and images location
_JS_SCRIPT = os.path.join(os.path.dirname(__file__), "generate_proposal.js")
_IMG_DIR    = os.path.join(os.path.dirname(__file__), "assets", "images")

def _find_node() -> str:
    """Return the node executable path."""
    node = shutil.which("node") or shutil.which("node.exe")
    if node:
        return node
    
    # Common Windows install paths as fallback
    candidates = [
        os.path.join(os.environ.get("ProgramFiles", r"C:\Program Files"), "nodejs", "node.exe"),
        os.path.join(os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)"), "nodejs", "node.exe")
    ]
    for path in candidates:
        if os.path.isfile(path):
            return path
            
    raise FileNotFoundError("Node.js not found. Please install it or add to PATH.")

def generate_proposal_docx(data: dict, output_path: str) -> str:
    """
    Generate a high-quality Proposal DOCX by delegating to generate_proposal.js (Node.js).
    This script handles the complex formatting (TOC, styles, tables) that 
    python-docx cannot easily replicate.
    """
    node_exe = _find_node()
    
    # Save a temporary JSON for the node script to read
    tmp_json = output_path.replace(".docx", "_payload.json")
    with open(tmp_json, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        
    cmd = [
        node_exe, 
        _JS_SCRIPT,
        "--data",   tmp_json,
        "--out",    output_path,
        "--images", _IMG_DIR
    ]
    
    logger.info(f"Generating proposal via Node.js: {output_path}")
    
    try:
        # Pass 1: Run node script to generate base document
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=120,
            check=False
        )
        
        if result.returncode != 0:
            error_msg = result.stderr or result.stdout or "Unknown Node script error"
            logger.error(f"Node.js generator failed:\n{error_msg}")
            raise RuntimeError(f"Proposal generator script failed: {error_msg}")
            
        # Pass 2: Python Post-processing to add Native TOC
        _add_native_toc_post_process(output_path)
            
    finally:
        # Cleanup temporary JSON
        if os.path.exists(tmp_json):
            try:
                os.remove(tmp_json)
            except OSError:
                pass
                
    return output_path

def _add_native_toc_post_process(file_path: str):
    """
    Opens the docx generated by Node and replaces the placeholder 
    with a real dynamic TOC field using python-docx + oxml.
    """
    from docx import Document
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    if not os.path.exists(file_path):
        return

    doc = Document(file_path)
    
    # 1. Find the placeholder paragraph
    placeholder_found = False
    for p in doc.paragraphs:
        if "(Generating dynamic TOC...)" in p.text:
            placeholder_found = True
            # Clear text
            p.text = ""
            
            # 2. Inject Native TOC field (OXML)
            # This is the "Magic" code to insert a real TOC field in Word
            paragraph = p._p
            
            run = OxmlElement('w:r')
            fldChar1 = OxmlElement('w:fldChar')
            fldChar1.set(qn('w:fldCharType'), 'begin')
            run.append(fldChar1)
            paragraph.append(run)
            
            run = OxmlElement('w:r')
            instrText = OxmlElement('w:instrText')
            instrText.set(qn('xml:space'), 'preserve')
            instrText.text = 'TOC \\o "1-3" \\h \\z \\u'
            run.append(instrText)
            paragraph.append(run)
            
            run = OxmlElement('w:r')
            fldChar2 = OxmlElement('w:fldChar')
            fldChar2.set(qn('w:fldCharType'), 'separate')
            run.append(fldChar2)
            paragraph.append(run)
            
            run = OxmlElement('w:r')
            t = OxmlElement('w:t')
            t.text = "Table of Contents (Click here, then press F9 to update)"
            run.append(t)
            paragraph.append(run)
            
            run = OxmlElement('w:r')
            fldChar3 = OxmlElement('w:fldChar')
            fldChar3.set(qn('w:fldCharType'), 'end')
            run.append(fldChar3)
            paragraph.append(run)
            break

    if placeholder_found:
        doc.save(file_path)
        logger.info(f"Native TOC field added to {file_path}")
    else:
        logger.warning(f"TOC Placeholder not found in {file_path}")
